apiVersion: v1
kind: Service
metadata:
  name: flask-ml-service
spec:
  selector:
    app: flask-ml
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ml
spec:
  selector:
    matchLabels:
      app: flask-ml
  replicas: 4
  template:
    metadata:
      labels:
        app: flask-ml
    spec:
      containers:
      - name: flask-ml
        image: flask-ml
        imagePullPolicy: Never
        ports:
        - containerPort: 5000